//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Fall2024_GraysonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public string Name { get; set; }
        public int ProjectMemberId { get; set; }
        public int TaskId { get; set; }
        public int DateKey { get; set; }
        public string Comment { get; set; }
        public string SourceCodeLocation { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string Description { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual Task Task { get; set; }
        public virtual ProjectMember ProjectMember { get; set; }
    }
}
