//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Fall2024_GraysonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int OfficeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
