//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP245_Fall2024_GraysonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsImage
    {
        public int SportsImageId { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string Heading { get; set; }
        public bool IsOnBanner { get; set; }
    }
}
